펫시터 지원하기 추가 하였습니다.
goorm-petmates/petmates_backend pull request #36
Opened 2024-02-18 07:10 UTC by Dominico-Yoon

펫시터 지원하기 추가 하였습니다.

2024-02-18 17:36 UTC, Timothy-Y-H-Lee commented on src/main/java/kr/co/petmates/api/bussiness/members/repository/MembersRepository.java
>      @EntityGraph(attributePaths = "authorities")
참고로, @EntityGraph(attributePaths = "authorities") 이 부분은 merge될 때, 일단 주석처리 될 꺼예요~

2024-02-18 18:08 UTC, Timothy-Y-H-Lee requested changes
오타, 깃 충돌 해결 요청 등의 코멘트를 남겼어요
확인 부탁드려요~

2024-02-19 03:07 UTC, Dominico-Yoon commented on src/main/java/kr/co/petmates/api/bussiness/petsitter/service/PetsitterPostService.java
> +    @Transactional(readOnly = true)
넵 수정 하였습니다.

2024-02-19 03:10 UTC, Dominico-Yoon commented on src/main/java/kr/co/petmates/api/bussiness/petsitter/service/PetsitterPostService.java
> +                petsitter.addVeiwCnt();
수정 완료했습니다.

2024-02-19 06:34 UTC, merged